export const PERMISSIONS = {
  // Users
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_DELETE: 'users:delete',

  // Roles
  ROLES_MANAGE: 'roles:manage',

  // Products
  PRODUCTS_READ: 'products:read',
  PRODUCTS_WRITE: 'products:write',
  PRODUCTS_DELETE: 'products:delete',

  // Categories
  CATEGORIES_READ: 'categories:read',
  CATEGORIES_WRITE: 'categories:write',
  CATEGORIES_DELETE: 'categories:delete',

  // News
  NEWS_READ: 'news:read',
  NEWS_WRITE: 'news:write',
  NEWS_PUBLISH: 'news:publish',
  NEWS_DELETE: 'news:delete',

  // Brands
  BRANDS_READ: 'brands:read',
  BRANDS_WRITE: 'brands:write',
  BRANDS_DELETE: 'brands:delete',

  // Certifications
  CERTIFICATIONS_READ: 'certifications:read',
  CERTIFICATIONS_WRITE: 'certifications:write',
  CERTIFICATIONS_DELETE: 'certifications:delete',

  // Careers
  CAREERS_READ: 'careers:read',
  CAREERS_WRITE: 'careers:write',
  CAREERS_DELETE: 'careers:delete',

  // Applicants
  APPLICANTS_READ: 'applicants:read',
  APPLICANTS_WRITE: 'applicants:write',

  // Inquiries
  INQUIRIES_READ: 'inquiries:read',
  INQUIRIES_RESPOND: 'inquiries:respond',
  INQUIRIES_DELETE: 'inquiries:delete',

  // Gallery
  GALLERY_READ: 'gallery:read',
  GALLERY_WRITE: 'gallery:write',
  GALLERY_DELETE: 'gallery:delete',

  // Testimonials
  TESTIMONIALS_READ: 'testimonials:read',
  TESTIMONIALS_WRITE: 'testimonials:write',
  TESTIMONIALS_DELETE: 'testimonials:delete',

  // Downloads
  DOWNLOADS_READ: 'downloads:read',
  DOWNLOADS_WRITE: 'downloads:write',
  DOWNLOADS_DELETE: 'downloads:delete',

  // Services
  SERVICES_READ: 'services:read',
  SERVICES_WRITE: 'services:write',
  SERVICES_DELETE: 'services:delete',

  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',

  // Media
  MEDIA_UPLOAD: 'media:upload',
  MEDIA_DELETE: 'media:delete',

  // Settings
  SETTINGS_READ: 'settings:read',
  SETTINGS_MANAGE: 'settings:manage',

  // Notifications
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_MANAGE: 'notifications:manage',

  // Audit Logs
  AUDIT_LOGS_READ: 'audit_logs:read',

  // Activity Logs
  ACTIVITY_LOGS_READ: 'activity_logs:read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Default permissions per role
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  super_admin: Object.values(PERMISSIONS) as Permission[],

  admin: [
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_WRITE, PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.CATEGORIES_READ, PERMISSIONS.CATEGORIES_WRITE, PERMISSIONS.CATEGORIES_DELETE,
    PERMISSIONS.NEWS_READ, PERMISSIONS.NEWS_WRITE, PERMISSIONS.NEWS_PUBLISH, PERMISSIONS.NEWS_DELETE,
    PERMISSIONS.BRANDS_READ, PERMISSIONS.BRANDS_WRITE, PERMISSIONS.BRANDS_DELETE,
    PERMISSIONS.CERTIFICATIONS_READ, PERMISSIONS.CERTIFICATIONS_WRITE, PERMISSIONS.CERTIFICATIONS_DELETE,
    PERMISSIONS.CAREERS_READ, PERMISSIONS.CAREERS_WRITE, PERMISSIONS.CAREERS_DELETE,
    PERMISSIONS.APPLICANTS_READ, PERMISSIONS.APPLICANTS_WRITE,
    PERMISSIONS.INQUIRIES_READ, PERMISSIONS.INQUIRIES_RESPOND, PERMISSIONS.INQUIRIES_DELETE,
    PERMISSIONS.GALLERY_READ, PERMISSIONS.GALLERY_WRITE, PERMISSIONS.GALLERY_DELETE,
    PERMISSIONS.TESTIMONIALS_READ, PERMISSIONS.TESTIMONIALS_WRITE, PERMISSIONS.TESTIMONIALS_DELETE,
    PERMISSIONS.DOWNLOADS_READ, PERMISSIONS.DOWNLOADS_WRITE, PERMISSIONS.DOWNLOADS_DELETE,
    PERMISSIONS.SERVICES_READ, PERMISSIONS.SERVICES_WRITE, PERMISSIONS.SERVICES_DELETE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MEDIA_UPLOAD, PERMISSIONS.MEDIA_DELETE,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.AUDIT_LOGS_READ,
    PERMISSIONS.ACTIVITY_LOGS_READ,
  ],

  editor: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.CATEGORIES_READ, PERMISSIONS.CATEGORIES_WRITE,
    PERMISSIONS.NEWS_READ, PERMISSIONS.NEWS_WRITE,
    PERMISSIONS.BRANDS_READ, PERMISSIONS.BRANDS_WRITE,
    PERMISSIONS.CERTIFICATIONS_READ, PERMISSIONS.CERTIFICATIONS_WRITE,
    PERMISSIONS.CAREERS_READ, PERMISSIONS.CAREERS_WRITE,
    PERMISSIONS.APPLICANTS_READ,
    PERMISSIONS.GALLERY_READ, PERMISSIONS.GALLERY_WRITE,
    PERMISSIONS.TESTIMONIALS_READ, PERMISSIONS.TESTIMONIALS_WRITE,
    PERMISSIONS.DOWNLOADS_READ, PERMISSIONS.DOWNLOADS_WRITE,
    PERMISSIONS.SERVICES_READ, PERMISSIONS.SERVICES_WRITE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  content_manager: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.NEWS_READ,
    PERMISSIONS.BRANDS_READ,
    PERMISSIONS.INQUIRIES_READ, PERMISSIONS.INQUIRIES_RESPOND,
    PERMISSIONS.APPLICANTS_READ,
    PERMISSIONS.GALLERY_READ,
    PERMISSIONS.TESTIMONIALS_READ,
    PERMISSIONS.DOWNLOADS_READ,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
};
